fsm:
  init_takeoff: 1.0
  lidar_avoidance_distance: 1.1
  global_pose_x_min: -30
  global_pose_y_min: -30
  global_pose_z_min: -0.2
  global_pose_x_max: 30.8
  global_pose_y_max: 30.8
  global_pose_z_max: 1.9

FSM_mode: 0
thrust_scale: 0.035
manual_trj_switch: false
target_x: 0.0
target_y: 0.0
target_z: 1.0
target_yaw: 0.0 #1.52
verbos: false