fsm:
  init_takeoff: 1.5
  lidar_avoidance_distance: 0.8
  global_pose_x_min: -1.0
  global_pose_y_min: -1.0
  global_pose_z_min: 0.5
  global_pose_x_max: 25
  global_pose_y_max: 25
  global_pose_z_max: 2.5

d0: 2.0
k0: 0.1
thrust_scale: 0.035
manual_trj_switch: false