fsm:
  init_takeoff: 0.8
  lidar_avoidance_distance: 1.0
  global_pose_x_min: -20
  global_pose_y_min: -20
  global_pose_z_min: -0.2
  global_pose_x_max: 20.8
  global_pose_y_max: 20.8
  global_pose_z_max: 1.5

FSM_mode: 1
d0: 3.0
k0: 0.1
thrust_scale: 0.035
manual_trj_switch: false
target_x: 0.0
target_y: 0.0
target_z: 0.8
target_yaw: 0.0 #1.52
verbos: false