mapfollower:
  init_takeoff: 0.8
  lidar_avoidance_distance: 1.0
  global_pose_x_min: -100
  global_pose_y_min: -100
  global_pose_z_min: 0.0
  global_pose_x_max: 100
  global_pose_y_max: 100
  global_pose_z_max: 3.0

